설명:
통계청 api 데이터
https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1B34E13&vw_cd=MT_ZTITLE&list_id=F_27&seqNo=&lang_mode=ko&language=kor&obj_var_id=&itm_id=&conn_path=MT_ZTITLE

받아서 csv파일로 만드는 ipynb 코드입니다.

In [47]:
import pandas as pd
import requests

url = 'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MzE5YTc5YzdmMmJhZmQ0NGUxMGI3NTZjMjY4ZjJkNjI=&itmId=T1+T4+T7+&objL1=0+1+2+3+4+5+6+7+8+9+A+B+C+D+E+F+G+H+I+J+&objL2=00+11+21+22+23+24+25+26+29+31+32+33+34+35+36+37+38+39+&objL3=ALL&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Y&newEstPrdCnt=10&prdInterval=1&outputFields=TBL_ID+TBL_NM+OBJ_ID+OBJ_NM+NM+ITM_ID+ITM_NM+UNIT_NM+PRD_DE+&orgId=101&tblId=DT_1B34E13'
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)

In [49]:
df.head(13)

,TBL_NM,PRD_DE,TBL_ID,ITM_NM,ITM_ID,UNIT_NM,C1_OBJ_NM,C2_OBJ_NM,C3_OBJ_NM,DT,C3,C2,C1,C1_NM,C2_NM,C3_NM
0,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2013,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,266257,0,00,0,계,전국,계
1,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2014,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,267692,0,00,0,계,전국,계
2,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2015,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,275895,0,00,0,계,전국,계
3,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2016,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,280827,0,00,0,계,전국,계
4,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2017,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,285534,0,00,0,계,전국,계
5,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2018,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,298820,0,00,0,계,전국,계
6,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2019,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,295110,0,00,0,계,전국,계
7,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2020,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,304948,0,00,0,계,전국,계
8,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2021,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,317680,0,00,0,계,전국,계
9,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2022,DT_1B34E13,사망자수,T1,명,사망원인별(50항목),시군구별,성별,372939,0,00,0,계,전국,계
10,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2013,DT_1B34E13,사망률,T4,십만명당,사망원인별(50항목),시군구별,성별,526.6,0,00,0,계,전국,계
11,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2014,DT_1B34E13,사망률,T4,십만명당,사망원인별(50항목),시군구별,성별,527.3,0,00,0,계,전국,계
12,시군구/사망원인(50항목)/성/ 사망자수 사망률 연령표준화 사망률(1998~),2015,DT_1B34E13,사망률,T4,십만명당,사망원인별(50항목),시군구별,성별,541.5,0,00,0,계,전국,계

In [50]:
final_data = pd.pivot_table(data=df, index=['PRD_DE','C1_NM', 'C2_NM', 'C3_NM', 'ITM_NM'], values='DT', aggfunc=['sum'])

In [52]:
final_data.to_csv('질병원인별_지역별_성별_사망자수통계.csv', encoding='utf-8-sig')